name: tg_reg_bot
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  teledart: ^0.6.1
  meta: ^1.16.0

  # DB
  hive_ce: ^2.8.0+2


dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
